server:
    port: 9898

spring:
  application:
    name: IDENTITY-SERVICE
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/authdb
    username: auth-team
    password: auth-team-pass
    driver-class-name: com.mysql.cj.jdbc.Driver
  config:
    import: configserver:http://localhost:9296
